version: '3.4'
services:
  postgres:
    container_name: thread_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=threads
      - POSTGRES_DB=threads
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # redis:
  #   container_name: thread_redis
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - mynetwork

volumes:
  postgres_data:



# also if u dont want to see the logs on the same terminal then run the following command
# docker-compose up -d
